### ISSUE TITLE
Trying to install with Meteor and getting some warnings and then cannot run it

### ISSUE THREAD

**Issue by adamgins** [jonathanasquier/stripe-pdf-invoice#3]
Hi, thanks for this package. 

I am trying to run with Meteor and when I install I get the following warnings:

```
Adams-MacBook-Pro:buzzy7 adamginsburg$ meteor npm install --save stripe-pdf-invoice
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
buzzy7@1.0.0 /Users/adamginsburg/Documents/Development/buzzy7
└─┬ stripe-pdf-invoice@1.0.7 
  ├── async@1.5.2 
  ├── image-size@0.3.5 
  ├─┬ jade@1.11.0 
  │ ├── character-parser@1.2.1 
  │ ├─┬ clean-css@3.4.19 
  │ │ ├─┬ commander@2.8.1 
  │ │ │ └── graceful-readlink@1.0.1 
  │ │ └─┬ source-map@0.4.4 
  │ │   └── amdefine@1.0.0 
  │ ├── commander@2.6.0 
  │ ├─┬ constantinople@3.0.2 
  │ │ └── acorn@2.7.0 
  │ ├─┬ jstransformer@0.0.2 
  │ │ ├── is-promise@2.1.0 
  │ │ └─┬ promise@6.1.0 
  │ │   └── asap@1.0.0 
  │ ├─┬ mkdirp@0.5.1 
  │ │ └── minimist@0.0.8 
  │ ├─┬ transformers@2.1.0 
  │ │ ├─┬ css@1.0.8 
  │ │ │ ├── css-parse@1.0.4 
  │ │ │ └── css-stringify@1.0.5 
  │ │ ├─┬ promise@2.0.0 
  │ │ │ └── is-promise@1.0.1 
  │ │ └─┬ uglify-js@2.2.5 
  │ │   ├─┬ optimist@0.3.7 
  │ │   │ └── wordwrap@0.0.3 
  │ │   └── source-map@0.1.43 
  │ ├─┬ uglify-js@2.7.0 
  │ │ ├── async@0.2.10 
  │ │ ├── source-map@0.5.6 
  │ │ ├── uglify-to-browserify@1.0.2 
  │ │ └─┬ yargs@3.10.0 
  │ │   ├── camelcase@1.2.1 
  │ │   ├─┬ cliui@2.1.0 
  │ │   │ ├─┬ center-align@0.1.3 
  │ │   │ │ ├─┬ align-text@0.1.4 
  │ │   │ │ │ ├─┬ kind-of@3.0.4 
  │ │   │ │ │ │ └── is-buffer@1.1.4 
  │ │   │ │ │ ├── longest@1.0.1 
  │ │   │ │ │ └── repeat-string@1.5.4 
  │ │   │ │ └── lazy-cache@1.0.4 
  │ │   │ ├── right-align@0.1.3 
  │ │   │ └── wordwrap@0.0.2 
  │ │   ├── decamelize@1.2.0 
  │ │   └── window-size@0.1.0 
  │ ├── void-elements@2.0.1 
  │ └─┬ with@4.0.3 
  │   ├── acorn@1.2.2 
  │   └── acorn-globals@1.0.9 
  ├── moment@2.14.1 
  ├─┬ request@2.74.0 
  │ ├── aws-sign2@0.6.0 
  │ ├── aws4@1.4.1 
  │ ├─┬ bl@1.1.2 
  │ │ └─┬ readable-stream@2.0.6 
  │ │   ├── core-util-is@1.0.2 
  │ │   ├── inherits@2.0.1 
  │ │   ├── isarray@1.0.0 
  │ │   ├── process-nextick-args@1.0.7 
  │ │   ├── string_decoder@0.10.31 
  │ │   └── util-deprecate@1.0.2 
  │ ├── caseless@0.11.0 
  │ ├─┬ combined-stream@1.0.5 
  │ │ └── delayed-stream@1.0.0 
  │ ├── extend@3.0.0 
  │ ├── forever-agent@0.6.1 
  │ ├── form-data@1.0.0-rc4 
  │ ├─┬ har-validator@2.0.6 
  │ │ ├─┬ chalk@1.1.3 
  │ │ │ ├── ansi-styles@2.2.1 
  │ │ │ ├── escape-string-regexp@1.0.5 
  │ │ │ ├─┬ has-ansi@2.0.0 
  │ │ │ │ └── ansi-regex@2.0.0 
  │ │ │ ├── strip-ansi@3.0.1 
  │ │ │ └── supports-color@2.0.0 
  │ │ ├── commander@2.9.0 
  │ │ ├─┬ is-my-json-valid@2.13.1 
  │ │ │ ├── generate-function@2.0.0 
  │ │ │ ├─┬ generate-object-property@1.2.0 
  │ │ │ │ └── is-property@1.0.2 
  │ │ │ ├── jsonpointer@2.0.0 
  │ │ │ └── xtend@4.0.1 
  │ │ └─┬ pinkie-promise@2.0.1 
  │ │   └── pinkie@2.0.4 
  │ ├─┬ hawk@3.1.3 
  │ │ ├── boom@2.10.1 
  │ │ ├── cryptiles@2.0.5 
  │ │ ├── hoek@2.16.3 
  │ │ └── sntp@1.0.9 
  │ ├─┬ http-signature@1.1.1 
  │ │ ├── assert-plus@0.2.0 
  │ │ ├─┬ jsprim@1.3.0 
  │ │ │ ├── extsprintf@1.0.2 
  │ │ │ ├── json-schema@0.2.2 
  │ │ │ └── verror@1.3.6 
  │ │ └─┬ sshpk@1.9.2 
  │ │   ├── asn1@0.2.3 
  │ │   ├── assert-plus@1.0.0 
  │ │   ├─┬ dashdash@1.14.0 
  │ │   │ └── assert-plus@1.0.0 
  │ │   ├── ecc-jsbn@0.1.1 
  │ │   ├─┬ getpass@0.1.6 
  │ │   │ └── assert-plus@1.0.0 
  │ │   ├── jodid25519@1.0.2 
  │ │   ├── jsbn@0.1.0 
  │ │   └── tweetnacl@0.13.3 
  │ ├── is-typedarray@1.0.0 
  │ ├── isstream@0.1.2 
  │ ├── json-stringify-safe@5.0.1 
  │ ├─┬ mime-types@2.1.11 
  │ │ └── mime-db@1.23.0 
  │ ├── node-uuid@1.4.7 
  │ ├── oauth-sign@0.8.2 
  │ ├── qs@6.2.1 
  │ ├── stringstream@0.0.5 
  │ ├── tough-cookie@2.3.1 
  │ └── tunnel-agent@0.4.3 
  ├─┬ stripe@3.9.0 
  │ └── lodash@3.10.1 
  ├── underscore@1.8.3 
  └─┬ wkhtmltopdf@0.1.6 
    └── slang@0.3.0 

npm WARN bl@0.7.0 requires a peer of stream-browserify@* but none was installed.
npm WARN buzzy7@1.0.0 No description
Adams-MacBook-
```

When I call the code, I get the following errors:

```
W20160814-00:27:20.161(10)? (STDERR) Error: /bin/sh: wkhtmltopdf: command not found
W20160814-00:27:20.162(10)? (STDERR)     at Socket.wkhtmltopdf.command (/Users/adamginsburg/Documents/Development/buzzy7/node_modules/wkhtmltopdf/index.js:97:17)
W20160814-00:27:20.162(10)? (STDERR)     at Socket.g (events.js:180:16)
W20160814-00:27:20.162(10)? (STDERR)     at Socket.emit (events.js:95:17)
W20160814-00:27:20.162(10)? (STDERR)     at Socket.<anonymous> (_stream_readable.js:765:14)
W20160814-00:27:20.163(10)? (STDERR)     at Socket.emit (events.js:92:17)
W20160814-00:27:20.163(10)? (STDERR)     at emitReadable_ (_stream_readable.js:427:10)
W20160814-00:27:20.163(10)? (STDERR)     at emitReadable (_stream_readable.js:423:5)
W20160814-00:27:20.163(10)? (STDERR)     at readableAddChunk (_stream_readable.js:166:9)
W20160814-00:27:20.163(10)? (STDERR)     at Socket.Readable.push (_stream_readable.js:128:10)
W20160814-00:27:20.163(10)? (STDERR)     at Pipe.onread (net.js:529:21)
=> Exited with code: 7

Unable to resolve some modules:

  "app.js" in
/Users/adamginsburg/Documents/Development/buzzy7/node_modules/stripe-pdf-invoice/package.json
(os.osx.x86_64)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save app.js
```

Any thoughts, please? Not sure if this would run with Meteor, but thought I'd give it a quick try.

**Comment by jonathanasquier** [comment]
Hi, stripe-pdf-invoice uses a node wrapper for wkhtmltopdf, make sure you have it installed in your system and available in your PATH, that's why it throws `Error: /bin/sh: wkhtmltopdf: command not found`
http://wkhtmltopdf.org/downloads.html

**Comment by adamgins** [comment]
thanks… hopes did not realize I had to install that. Probably a show stopper has hosting company won’t be able to do that

Adam Ginsburg
adam.ginsburg@buzzy.buzz
tel: +61 411 151 732
www.buzzy.buzz

**Comment by jonathanasquier** [comment]
Feel free to reopen if needed.
